import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import { Nunito } from "next/font/google";
import Footer from "./components/footer";
import { ToastContainer } from 'react-toastify';

const nunito = Nunito({
  variable: "--font-nunito", // To‘g‘ri nom
  subsets: ["latin"],
  weight: ["400", "700"], // Faqat kerakli vaznlarni yuklash
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable} suppressHydrationWarning>
      <body className="antialiased">
        <Navbar />
        {children}
        <ToastContainer position="bottom-right"/>
        <Footer/>
      </body>
    </html>
  );
}
